### ISSUE TITLE
Change order of columns in rohdaten file

### ISSUE THREAD

**Issue by adrianrupp88** [awelZH/nis_meas_school#18]
According to confluence doc

**Comment by adrianrupp88** [comment]
@philbosch Ich könnte diesen Issue gut übernehmen. Lass mich wissen, wenn ich es umsetzen sollte.

**Comment by philbosch** [comment]
> @philbosch Ich könnte diesen Issue gut übernehmen. Lass mich wissen, wenn ich es umsetzen sollte.

@adrianrupp88 steht für heute Abend auf der Agenda. Falls du es davor erledigen möchtest, sehr gerne :)

**Comment by adrianrupp88** [comment]
Alles klar, danke. Ich übernehme diesen Issue
