### ISSUE TITLE
improve documentation

### ISSUE THREAD

**Issue by philbosch** [awelZH/nis_meas_school#31]
Dokumentation in Richtung https://github.com/statistikZH/decarb_monitoring entwickeln.

- [x] troubleshooting section
- [x] Initiales Aufsetzen
- [x] Szenarien

**Comment by adrianrupp88** [comment]
Hey @philbosch & @CGRBZH 
Habe einen neuen Branch für diesen Issue aufgemacht und das Initiales Aufsetzen, die Szenarien und eine troubleshooting section im Readme eingefügt.
Falls ihr an der Doku arbeitet, könnt ihr den Branch #31-improve-doc verwenden.
