### ISSUE TITLE
Default auf Veröffentlichen setzen

### ISSUE THREAD

**Issue by philbosch** [awelZH/nis_meas_school#41]
Die beiden Zeilen müssten angepasst werden:

https://github.com/awelZH/nis_meas_school/blob/f8dc76e5b59a4cc347be35388f6192744f760f1d/R/update.R#L63

https://github.com/awelZH/nis_meas_school/blob/f8dc76e5b59a4cc347be35388f6192744f760f1d/R/update.R#L87

**Comment by gma-lks** [comment]
Status in https://github.com/awelZH/nis_meas_school/blob/f8dc76e5b59a4cc347be35388f6192744f760f1d/R/update.R#L63 und https://github.com/awelZH/nis_meas_school/blob/f8dc76e5b59a4cc347be35388f6192744f760f1d/R/update.R#L87 von 1 (Entwurf) auf 3 (publiziert) gesetzt.
